### ISSUE TITLE
Is there any way to get event excerpt and display in custom event listing template ?

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [eventespresso/event-espresso-legacy#2]
get_the_excerpt(); does not retieve the excerpt , please let me know if there is any other function to achieve it.

event_list_display.php

```
<div class="PostExcerpt">
    <h2>
        <?php if (strlen($event_desc) > 750){?> <a href="<?php echo $registration_url; ?>"><?php echo stripslashes_deep($event_name) ?> </a> <?php } else { echo stripslashes_deep($event_name); }?>
    </h2>
    <div class="PostMeta">by <?php the_author(); ?> on <?php the_date(); ?></div>

    <span style="font-size: 18px;margin: 38px 0 24px;">
        <b><em><?php echo event_date_display($start_date, get_option('date_format')) ?> <?php if($event_meta['start_time']){?>- <?php $time = strtotime($event_meta['start_time']); echo date("g:i A", $time);} ?></em></b>
    </span>

    <p><?php echo get_the_excerpt(); ?></p>

    <div class="PostEvent">
        <p>
           <?php echo stripslashes_deep($v_title); ?><br />
           <?php echo stripslashes_deep($location); ?>
        </p>
    </div>
    <?php if(!is_page(44)){ echo $google_map_link; ?> | <a href="<?php echo $registration_url; ?>">More Info</a> <?php } ?>
</div>
```

**Comment by nerrad** [comment]
Hi, apologies because it wasn't already clear, but we just [updated the `README.md` for this repository](https://github.com/eventespresso/event-espresso-legacy/blob/master/README.md).  Before I could answer your question in the other thread, you posted in here.

We are a smaller team so we have to focus our resources for support on paying customers (especially for products that are legacy products).

**Comment by PrafullaKumarSahu** [comment]
the simple for of the same question is in wordpress posts there is the_excerpt() or get_the_excerpt() , is there anything like that for events ??

**Comment by joshfeck** [comment]
Did you post the same question in the support forums in [this thread](https://eventespresso.com/topic/is-there-any-way-i-can-add-custom-excerpt-to-event-like-wordpress-posts/)? If so, please try to post your questions in one place. Thank you.

**Comment by PrafullaKumarSahu** [comment]
I was not getting reply from any of it thank you so much for your kindness.

if some having same question please visit 

https://eventespresso.com/topic/is-there-any-way-i-can-add-custom-excerpt-to-event-like-wordpress-posts/
