### ISSUE TITLE
WordPress 5.4 with Event Espresso 3 - 404 Errors Unless Logged In as Admin

### ISSUE THREAD

**Issue by own3mall** [eventespresso/event-espresso-legacy#23]
The latest version of Event Espresso 3 doesn't appear to work properly in WordPress 5.4.

When I try to register for an event, I get a 404 not found page.  However, I don't get the 404 page when I'm logged in as an administrator.

URLs such as:

/event-registration/?ee=14546
/?page_id=18680&ee=14546

Result in a 404 not found page when I'm not logged in as an administrator, but works properly when I am logged in with an administrator account.  I don't believe it's a permalinks issue.  I am running nginx.

It's happening for all of my events even though they were setup properly.  I'm not sure when this issue started happening, but it is sometime after WordPress was updated from 5.2 to 5.3 and then to 5.4.

Any idea?

The espresso log when logged in as an admin matches the espresso log entries generated when not logged in, so I have no idea why this is happening.

[ 2020-04-20 15:00:28 ]  espresso.php
        VARS : ee = 14546
[ 2020-04-20 15:00:28 ]  registration_page.php  -> FILE LOADED
[ 2020-04-20 15:00:28 ]  cart.php  -> FILE LOADED
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_load_pricing_functions
[ 2020-04-20 15:00:28 ]  espresso-multi-registration.php  -> load_event_espresso_cart_widget
[ 2020-04-20 15:00:28 ]  espresso.php  -> load_event_espresso_widget
[ 2020-04-20 15:00:28 ]  espresso.php  -> ee_init_session
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_export_certificate
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_export_ticket
[ 2020-04-20 15:00:28 ]  espresso.php  -> event_espresso_run
[ 2020-04-20 15:00:28 ]  registration_page.php  -> register_attendees
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  cart.php  -> event_espresso_cart_link
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_member_price_select_action
[ 2020-04-20 15:00:28 ]  member_functions.php  -> event_espresso_price_dropdown
        346
[ 2020-04-20 15:00:28 ]  pricing.php  -> early_discount_amount
[ 2020-04-20 15:00:28 ]  ical.php  -> espresso_ical_prepare_by_meta
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_load_javascript_files
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_register_validation_for_shortcodes
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_load_jquery
[ 2020-04-20 15:00:28 ]  espresso.php  -> add_event_espresso_stylesheet
[ 2020-04-20 15:00:28 ]  espresso.php  -> add_espresso_themeroller_stylesheet
[ 2020-04-20 15:00:28 ]  espresso.php  -> espresso_info_header

[ 2020-04-20 15:00:29 ]  espresso.php
        VARS : ee = 14546
[ 2020-04-20 15:00:29 ]  registration_page.php  -> FILE LOADED
[ 2020-04-20 15:00:29 ]  cart.php  -> FILE LOADED
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_load_pricing_functions
[ 2020-04-20 15:00:29 ]  espresso-multi-registration.php  -> load_event_espresso_cart_widget
[ 2020-04-20 15:00:29 ]  espresso.php  -> load_event_espresso_widget
[ 2020-04-20 15:00:29 ]  espresso.php  -> ee_init_session
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_export_certificate
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_export_ticket
[ 2020-04-20 15:00:29 ]  espresso.php  -> event_espresso_run
[ 2020-04-20 15:00:29 ]  registration_page.php  -> register_attendees
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  cart.php  -> event_espresso_cart_link
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_member_price_select_action
[ 2020-04-20 15:00:29 ]  member_functions.php  -> event_espresso_price_dropdown
        346
[ 2020-04-20 15:00:29 ]  pricing.php  -> early_discount_amount
[ 2020-04-20 15:00:29 ]  ical.php  -> espresso_ical_prepare_by_meta
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  member_functions.php  -> espresso_members_installed
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_load_javascript_files
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_register_validation_for_shortcodes
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_load_jquery
[ 2020-04-20 15:00:29 ]  espresso.php  -> add_event_espresso_stylesheet
[ 2020-04-20 15:00:29 ]  espresso.php  -> add_espresso_themeroller_stylesheet
[ 2020-04-20 15:00:29 ]  espresso.php  -> espresso_info_header

[ 2020-04-20 15:00:30 ]  espresso.php
        VARS : _ajax_nonce = e0c75a17c5 & action = coderockz_woo_delivery_get_orders & onlyDeliveryTime = true & date = 04/20/2020
[ 2020-04-20 15:00:30 ]  registration_page.php  -> FILE LOADED
[ 2020-04-20 15:00:30 ]  cart.php  -> FILE LOADED
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_load_pricing_functions
[ 2020-04-20 15:00:30 ]  espresso-multi-registration.php  -> load_event_espresso_cart_widget
[ 2020-04-20 15:00:30 ]  espresso.php  -> load_event_espresso_widget
[ 2020-04-20 15:00:30 ]  espresso.php  -> ee_init_session
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_version
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_export_certificate
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_export_ticket
[ 2020-04-20 15:00:30 ]  espresso.php  -> ee_check_for_export

[ 2020-04-20 15:00:30 ]  espresso.php
        VARS :
[ 2020-04-20 15:00:30 ]  registration_page.php  -> FILE LOADED
[ 2020-04-20 15:00:30 ]  cart.php  -> FILE LOADED
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_load_pricing_functions
[ 2020-04-20 15:00:30 ]  espresso-multi-registration.php  -> load_event_espresso_cart_widget
[ 2020-04-20 15:00:30 ]  espresso.php  -> load_event_espresso_widget
[ 2020-04-20 15:00:30 ]  espresso.php  -> ee_init_session
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_export_certificate
[ 2020-04-20 15:00:30 ]  espresso.php  -> espresso_export_ticket

[ 2020-04-20 15:00:31 ]  espresso.php
        VARS : cf_action = grp_auto_save & place_id = ChIJObKoqTtPE4cRy3jcOXCwC_I & min_filter = 4 & reviews_lang =  & ver = 1587394832059
[ 2020-04-20 15:00:31 ]  registration_page.php  -> FILE LOADED
[ 2020-04-20 15:00:31 ]  cart.php  -> FILE LOADED
[ 2020-04-20 15:00:31 ]  espresso.php  -> espresso_load_pricing_functions
[ 2020-04-20 15:00:31 ]  espresso-multi-registration.php  -> load_event_espresso_cart_widget
[ 2020-04-20 15:00:31 ]  espresso.php  -> load_event_espresso_widget
[ 2020-04-20 15:00:31 ]  espresso.php  -> ee_init_session

**Comment by joshfeck** [comment]
Hi,

We do not actually use GitHub for support, we've answered your question about this in the support forums.
